name: Image build
on:
  workflow_dispatch:
  push:
    tags:
    - v*
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: kaniko-${{ github.event.repository.name }}
    container:
      image: ghcr.io/osscontainertools/kaniko:v1.27.2-debug
    permissions:
      contents: read
      packages: write
    steps:
    - name: Build and release container
      run: |
        set -e
        cat > $DOCKER_CONFIG/config.json <<EOF
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n ${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }} | base64 -w0)"
            }
          }
        }
        EOF

        executor \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="ghcr.io/${{ github.repository }}:${{ github.head_ref || github.ref_name }}" \
          --image-download-retry=4 \
          --image-fs-extract-retry=4 \
          --push-retry=4 \
          --snapshot-mode=redo \
          --use-new-run \
          --single-snapshot \
          --cleanup \
          --cache=false

  cleanup:
    needs:
    - build
    runs-on: kaniko-${{ github.event.repository.name }}
    container:
      image: docker.io/node:25.9.0-alpine
    permissions:
      packages: write
    steps:
    - name: Remove old container images
      uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
      with:
        package-name: ${{ github.event.repository.name }}
        package-type: container
        min-versions-to-keep: 6
        ignore-versions: latest
        token: ${{ secrets.GITHUB_TOKEN }}